name: Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  build-deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build (staging)
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.STAGING_API_URL }}
          STAGING_DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
          STAGING_JWT_SECRET: ${{ secrets.STAGING_JWT_SECRET }}
        run: npm run build:staging

      - name: Deploy to staging
        run: echo "Add your hosting deployment command here"
