name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  build-deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build (production)
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.PROD_API_URL }}
          PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          PROD_JWT_SECRET: ${{ secrets.PROD_JWT_SECRET }}
        run: npm run build:production

      - name: Deploy to production
        run: echo "Add your hosting deployment command here"
